tempo:
  # Specific commit for reproducibility
  tag: main-814c1c6
    
  # Metrics generator - The key feature for traces → metrics integration
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://monitoring-kube-prometheus-prometheus:9090/api/v1/write"
      
  # Enable service graphs and span metrics
  overrides:
    defaults:
      metrics_generator:
        processors: [service-graphs, span-metrics, local-blocks]

# Enable persistence for realistic setup
persistence:
  enabled: true
